#ifndef APCAM_TARGET_MT11_H
#define APCAM_TARGET_MT11_H

/* Target properties shared by firmware, web UI and generated SITL data.
 * FOV calibration retains existing measurements/nominal values; see README. */
#define APCAM_NAME "mt11"
#define APCAM_PRODUCT_NAME "MT11"
#define APCAM_MODEL_NAME "MT11"
#define APCAM_MANUFACTURER "SIYI"
#define APCAM_NUM_LENSES 3
#define APCAM_NUM_STREAMS 2
#define APCAM_STREAM1_LENS_MASK 3
#define APCAM_STREAM2_LENS_MASK 4
#define APCAM_HAVE_PHOTO 1
#define APCAM_HAVE_ZOOM 1
#define APCAM_NUM_RECORDING_CHANNELS 2
#define APCAM_VENDOR_PROTOCOL APCAM_PROTOCOL_SIYI
#define APCAM_HAVE_THERMAL 1
#define APCAM_HAVE_LIDAR 1
#define APCAM_ZOOM_NATIVE_RATE 0
#define APCAM_ZOOM_CONTROL_MAX APCAM_ZOOM_MAX
#define APCAM_WEB_CONTROL_MAVLINK 0
#define APCAM_HAVE_OVERLAY_RECORDING_SELECT 1
#define APCAM_HAVE_GIMBAL_RATES 1
#define APCAM_SUPPRESS_DUPLICATE_ANGLES 1
#define APCAM_WEB_CENTER_COMMAND 3
#define APCAM_HAVE_OPTICAL_ZOOM 1
#define APCAM_HAVE_FOCUS 1
#define APCAM_HAVE_IMAGE_CONTROLS 1
#define APCAM_HAVE_EXTERNAL_UART 1
#define APCAM_HAVE_SSH_KEYS 1
#define APCAM_HAVE_SOC_TEMPERATURE 1
#define APCAM_VENDOR_PORT 37260
#define APCAM_WEB_PORT 80
#define APCAM_LENS1_TYPE APCAM_LENS_TYPE_RGB
#define APCAM_LENS1_NAME "Wide RGB"
#define APCAM_LENS1_FOV_H 88.0f
#define APCAM_LENS1_FOV_H_TELE 0.0f
#define APCAM_LENS1_FOV_MODEL APCAM_FOV_FOCAL_LENGTH
#define APCAM_LENS1_OPTICAL_ZOOM_MAX 1
#define APCAM_LENS1_WIDTH 3840
#define APCAM_LENS1_HEIGHT 2160
#define APCAM_ZOOM_MAX 10.0f
#define APCAM_FRAME_RATE 30
#define APCAM_THERMAL_FRAME_RATE 25
#define APCAM_THERMAL_STREAM_WIDTH 1280
#define APCAM_THERMAL_STREAM_HEIGHT 720
#define APCAM_MAIN_RESOLUTIONS 7
#define APCAM_SUB_RESOLUTIONS 7
#define APCAM_RECORDING_RESOLUTIONS 7
#define APCAM_STREAM_CODECS 3
#define APCAM_DEFAULT_MAIN_RESOLUTION 1
#define APCAM_DEFAULT_SUB_RESOLUTION 0
#define APCAM_DEFAULT_RECORDING_RESOLUTION 1
#define APCAM_DEFAULT_SYSTEM_ID 0
#define APCAM_DEFAULT_POSITION_TARGETING 1
#define APCAM_DEFAULT_ORIENTATION 0
#define APCAM_DEFAULT_PHOTO_SCOPE 1
#define APCAM_DEFAULT_TIMEZONE "GMT-10"
#define APCAM_GIMBAL_PITCH_MIN -90.0f
#define APCAM_GIMBAL_PITCH_MAX 30.0f
#define APCAM_GIMBAL_YAW_CONTINUOUS 1
#define APCAM_GIMBAL_YAW_MIN -180.0f
#define APCAM_GIMBAL_YAW_MAX 180.0f
#define APCAM_GIMBAL_RATE_MAX 60.0f
/* MT11 bench BIN: normalized yaw speed 100 is approximately 100 deg/s. */
#define APCAM_VENDOR_YAW_RATE_FULL_SCALE 100.0f
#define APCAM_VENDOR_PITCH_RATE_FULL_SCALE 100.0f
/* Isolated upright bench sweeps, 2026-09-15: both axes hold still at
 * +/-1..5; above the threshold motion is approximately 1 deg/s per command
 * unit. Pitch measured through +/-100, yaw has more noise and asymmetry.
 * These are physical responses, separate from requested-rate conversion.
 * Inverted operation and hysteresis still need independent verification. */
#define APCAM_SIM_PITCH_RATE_CURVE {-100, -100, -6, -6, -5, 0, 0, 0, 5, 0, 6, 6, 100, 100}
#define APCAM_SIM_YAW_RATE_CURVE {-100, -100, -6, -6, -5, 0, 0, 0, 5, 0, 6, 6, 100, 100}
/* Approximate command/actuator lag from onset and stopping motion; includes
 * unseparated transport/feedback latency. See docs/mt11-rate-calibration.md. */
#define APCAM_SIM_RATE_TIME_CONSTANT 0.04f

#define APCAM_LENS2_TYPE APCAM_LENS_TYPE_RGB
#define APCAM_LENS2_NAME "Zoom RGB"
#define APCAM_LENS2_FOV_H 31.3613561f
#define APCAM_LENS2_BASE_MAGNIFICATION 3.44f
#define APCAM_LENS2_OPTICAL_ZOOM_MAX 3.2f
#define APCAM_LENS2_WIDTH 3840
#define APCAM_LENS2_HEIGHT 2160
#define APCAM_LENS3_TYPE APCAM_LENS_TYPE_THERMAL
#define APCAM_LENS3_NAME "Thermal"
#define APCAM_LENS3_FOV_H 24.2f
#define APCAM_LENS3_OPTICAL_ZOOM_MAX 1
#define APCAM_LENS3_WIDTH 640
#define APCAM_LENS3_HEIGHT 512
#define APCAM_GIMBAL_FEEDBACK_UPRIGHT_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, -1}
#define APCAM_GIMBAL_FEEDBACK_UPRIGHT_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_FEEDBACK_INVERTED_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, -1}
#define APCAM_GIMBAL_FEEDBACK_INVERTED_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_PRIVATE_FEEDBACK_UPRIGHT_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, 1}
#define APCAM_GIMBAL_PRIVATE_FEEDBACK_UPRIGHT_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_PRIVATE_FEEDBACK_INVERTED_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, 1}
#define APCAM_GIMBAL_PRIVATE_FEEDBACK_INVERTED_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_ANGLE_COMMAND_UPRIGHT_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, -1}
#define APCAM_GIMBAL_ANGLE_COMMAND_UPRIGHT_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_ANGLE_COMMAND_INVERTED_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, -1}
#define APCAM_GIMBAL_ANGLE_COMMAND_INVERTED_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_RATE_COMMAND_UPRIGHT_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, 1}
#define APCAM_GIMBAL_RATE_COMMAND_UPRIGHT_OFFSET {0, 0, 0}
#define APCAM_GIMBAL_RATE_COMMAND_INVERTED_MATRIX {1, 0, 0, 0, 1, 0, 0, 0, 1}
#define APCAM_GIMBAL_RATE_COMMAND_INVERTED_OFFSET {0, 0, 0}

/* Platform paths are consumed only by the web service. */
#ifdef APCAM_WEB_BUILD
#define FIRMWARE_PREFIX "MT11_FW_"
#define APP_SELECTION_DIR APP_DIR
#define APP_STORAGE_PATH "/app"
#endif

#endif
